In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

## Data Selection

In [10]:
# Project paths
DATA_PATH = Path("../data/raw/CarsData.csv")

cars = pd.read_csv(DATA_PATH)
print(f"The dataset has {cars.shape[0]} rows and {cars.shape[1]} columns.")

The dataset has 97712 rows and 10 columns.

In [11]:
cars.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize', 'Manufacturer'],
      dtype='str')

In [12]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 97712 entries, 0 to 97711
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         97712 non-null  str
 1   year          97712 non-null  int64
 2   price         97712 non-null  int64
 3   transmission  97712 non-null  str
 4   mileage       97712 non-null  int64
 5   fuelType      97712 non-null  str
 6   tax           97712 non-null  int64
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   Manufacturer  97712 non-null  str
dtypes: float64(2), int64(4), str(4)
memory usage: 7.5 MB

In [14]:
cars.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Manufacturer
0,I10,2017,7495,Manual,11630,Petrol,145,60.10,1.00,hyundi
1,Polo,2017,10989,Manual,9200,Petrol,145,58.90,1.00,volkswagen
2,2 Series,2019,27990,Semi-Auto,1614,Diesel,145,49.60,2.00,BMW
3,Yeti Outdoor,2017,12495,Manual,30960,Diesel,150,62.80,2.00,skoda
4,Fiesta,2017,7999,Manual,19353,Petrol,125,54.30,1.20,ford

In [13]:
cars.describe()

          year     price   mileage      tax      mpg  engineSize
count 97712.00  97712.00  97712.00 97712.00 97712.00    97712.00
mean   2017.07  16773.49  23219.48   120.14    55.21        1.66
std       2.12   9868.55  21060.88    63.36    16.18        0.56
min    1970.00    450.00      1.00     0.00     0.30        0.00
25%    2016.00   9999.00   7673.00   125.00    47.10        1.20
50%    2017.00  14470.00  17682.50   145.00    54.30        1.60
75%    2019.00  20750.00  32500.00   145.00    62.80        2.00
max    2024.00 159999.00 323000.00   580.00   470.80        6.60

## Data Cleaning